// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdtdahstklshhcplurzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkdGRhaHN0a2xzaGhjcGx1cnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MzcxODksImV4cCI6MjA1MTUxMzE4OX0.fDvPeL9XyEN-dZoSMcHWKcgfbmgAwAQTNWv-18Sypmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);